### ISSUE TITLE
Different colors for meetings

### ISSUE THREAD

**Issue by vjeux** [eendeego/unicalcorn#1]
Right now, the display is a white line for the beginning of a meeting and then a number of lines for each subsequent 15 minutes for the duration of the meeting. This is not very clear to me. I would want to see how it looks if we assign a different color for each meeting and put all the 15 minutes lines of that same color. I have a feeling that it would feel better.

**Comment by eendeego** [comment]
There'll be two new options to address this:
- Use fixed set of colors (current implementation) vs Use a sequence of colors (akin to a D3 category color scale);
- Enable/Disable the white border lines, which will no longer required to mark boundaries;

**Comment by eendeego** [comment]
"Enable/Disable the white border lines" is now part of the color scheme definition.
